/**
 * The persistence foundation every entity in every module extends.
 *
 * <p>The base entity carries two identifiers, and the distinction between them is the single most
 * load-bearing convention in the codebase:
 *
 * <ul>
 *   <li>a numeric surrogate key, which is <b>module-private</b> — it never appears in a published type's
 *       signature, never in a URL, never in an event payload;</li>
 *   <li>a {@code uuid}, generated by the <b>database</b>, which is the only handle allowed to cross a
 *       module boundary.</li>
 * </ul>
 *
 * <p>Generating the uuid in the database rather than in Java is what lets a row be inserted by a plain SQL
 * migration or a data fix and still be addressable — the identifier is a property of the row, not of the
 * process that happened to create it.
 *
 * <p>Consequences to get right when this is implemented: the uuid field is not insertable (it is read back
 * after insert), it transitions from null to a value at that moment, and therefore {@code hashCode} must
 * not be derived from it — an entity whose hash changes mid-transaction is stranded in the wrong bucket of
 * any collection holding it.
 */
package tz.co.otapp.buscore.shared.abstraction;
