-- identity-access V1 — staff login identities and their password material.
--
-- Every table carries the four columns BaseEntity supplies: id, uid, created_at, updated_at.
--
-- NOTE ON uid: there is deliberately NO DEFAULT on it. The application mints a UUIDv7 in Java at
-- construction, which is what lets an entity's uid exist before it is flushed and therefore be safe to
-- use in equals/hashCode. PostgreSQL 18 could generate one with uuidv7(), and a row inserted by hand
-- here should use that — but the application must not rely on it, because a database-assigned uid does
-- not exist until the row is written, and code that needs it earlier would silently see null.
--
-- Timestamps are plain `timestamp` holding UTC, never `timestamptz`. Hibernate maps Instant to
-- timestamptz by default, so `spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type: TIMESTAMP`
-- is what keeps ddl-auto=validate agreeing with this file. Without that property, validation fails on
-- every table in the system, starting with this one.

CREATE TABLE staff_identities
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid           uuid         NOT NULL,
    username      varchar(64)  NOT NULL,
    email         varchar(128) NOT NULL,
    display_name  varchar(128) NOT NULL,
    tenancy       varchar(32)  NOT NULL,
    status        varchar(32)  NOT NULL,
    created_at    timestamp    NOT NULL,
    updated_at    timestamp    NOT NULL
);

-- The handle every other module holds. Unique because a duplicate would make a uid ambiguous, which is
-- the one thing it may never be.
CREATE UNIQUE INDEX ux_staff_identities_uid ON staff_identities (uid);

-- CASE-INSENSITIVE UNIQUENESS, done functionally so the original casing is preserved for display.
-- Defeats: `Alice` and `alice` existing as two accounts, which is indistinguishable to a human reading a
-- list and is a straightforward impersonation route.
-- Consequence for repositories: a lookup MUST use the case-insensitive query. A case-sensitive one does
-- not fail — it silently bypasses this guarantee at read time and finds nothing for `Alice`.
CREATE UNIQUE INDEX ux_staff_identities_username_lower ON staff_identities (lower(username));
CREATE UNIQUE INDEX ux_staff_identities_email_lower ON staff_identities (lower(email));

-- AT MOST ONE ROOT, EVER. Uniqueness declared on the discriminator and restricted to the rows carrying
-- it: every such row holds the identical value 'ROOT', so the index admits exactly one.
-- Defeats: two concurrent bootstraps both observing "no ROOT exists" and both inserting. A service-layer
-- existsBy check cannot prevent that — both transactions see the same empty table. ROOT bypasses the
-- permission system entirely, so a second one is a second master key.
CREATE UNIQUE INDEX ux_staff_identities_single_root
    ON staff_identities (tenancy) WHERE tenancy = 'ROOT';

CREATE TABLE staff_credentials
(
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                  uuid         NOT NULL,
    staff_identity_id    bigint       NOT NULL REFERENCES staff_identities (id),
    password_hash        varchar(255) NOT NULL,
    password_updated_at  timestamp    NOT NULL,
    failed_attempts      integer      NOT NULL DEFAULT 0,
    locked_until         timestamp,
    must_change_password boolean      NOT NULL DEFAULT false,
    created_at           timestamp    NOT NULL,
    updated_at           timestamp    NOT NULL
);

CREATE UNIQUE INDEX ux_staff_credentials_uid ON staff_credentials (uid);

-- ONE CREDENTIAL PER IDENTITY, enforced by making the foreign key itself unique.
-- Defeats: two live passwords on one account, where only one of them carries the failure counter — so an
-- attacker guessing against the other is never locked out. It is also what makes a repository lookup by
-- identity legitimately return at most one row rather than a list nobody checks the size of.
CREATE UNIQUE INDEX ux_staff_credentials_identity ON staff_credentials (staff_identity_id);
