-- identity-access V2 — roles, permissions, and the two grants that connect them.
--
-- THE SHAPE: a staff member holds ROLES; a role holds PERMISSIONS; a route requires a PERMISSION.
-- Roles exist so that granting is manageable — nobody assigns forty permissions by hand — but the runtime
-- check is always on the permission. That indirection is why a role can be renamed or recomposed without
-- touching a single @PreAuthorize.
--
-- BOTH JOIN TABLES ARE FULL TABLES, with their own id, uid and timestamps, rather than bare composite-key
-- link tables. A grant is a row in its own right: it was made at a time, and later it will be made BY
-- somebody. Modelling it as an anonymous pair leaves nowhere to record either.

CREATE TABLE permissions
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         uuid         NOT NULL,
    code        varchar(128) NOT NULL,
    description varchar(512) NOT NULL,
    created_at  timestamp    NOT NULL,
    updated_at  timestamp    NOT NULL
);

CREATE UNIQUE INDEX ux_permissions_uid ON permissions (uid);

-- The code is the contract a route names. Duplicates would make "does the caller hold X" ambiguous, and
-- the seed below relies on this to be idempotent.
CREATE UNIQUE INDEX ux_permissions_code ON permissions (code);

CREATE TABLE roles
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         uuid         NOT NULL,
    code        varchar(64)  NOT NULL,
    name        varchar(128) NOT NULL,
    description varchar(512) NOT NULL,
    -- Which class of staff may hold this role. A role meant for operator staff must not be grantable to a
    -- partner: the grant surface checks this, and storing it here is what lets it.
    holder_tenancy varchar(32) NOT NULL,
    -- Archived roles cannot be granted. Nullable rather than a boolean so the moment is recorded too.
    archived_at timestamp,
    created_at  timestamp    NOT NULL,
    updated_at  timestamp    NOT NULL
);

CREATE UNIQUE INDEX ux_roles_uid ON roles (uid);
CREATE UNIQUE INDEX ux_roles_code ON roles (code);

CREATE TABLE role_permissions
(
    id            bigint    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid           uuid      NOT NULL,
    role_id       bigint    NOT NULL REFERENCES roles (id),
    permission_id bigint    NOT NULL REFERENCES permissions (id),
    created_at    timestamp NOT NULL,
    updated_at    timestamp NOT NULL
);

CREATE UNIQUE INDEX ux_role_permissions_uid ON role_permissions (uid);

-- COMPOSITE UNIQUENESS IS WHAT MAKES A GRANT IDEMPOTENT. Granting the same permission twice inserts one
-- row or fails; it never produces two, so revoking removes the grant rather than half of it. This is also
-- why the grant endpoints need no idempotency key.
CREATE UNIQUE INDEX ux_role_permissions_pair ON role_permissions (role_id, permission_id);

-- Revocation deletes by role, and the seed rewrites a role's permission set wholesale. Postgres does not
-- index the referencing side of a foreign key automatically, so without this both scan the table.
CREATE INDEX ix_role_permissions_role ON role_permissions (role_id);

CREATE TABLE staff_roles
(
    id                bigint    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid               uuid      NOT NULL,
    staff_identity_id bigint    NOT NULL REFERENCES staff_identities (id),
    role_id           bigint    NOT NULL REFERENCES roles (id),
    created_at        timestamp NOT NULL,
    updated_at        timestamp NOT NULL
);

CREATE UNIQUE INDEX ux_staff_roles_uid ON staff_roles (uid);

-- Same reasoning as above: one row per (person, role), so a double grant is not two rows one of which
-- survives a revoke.
CREATE UNIQUE INDEX ux_staff_roles_pair ON staff_roles (staff_identity_id, role_id);

-- Every sign-in resolves the holder's permissions through this column.
CREATE INDEX ix_staff_roles_staff_identity ON staff_roles (staff_identity_id);
