-- identity-access V3 — the authentication audit trail.
--
-- Separate from the general audit trail in the shared kernel, and deliberately so. This one records
-- SECURITY TELEMETRY: who tried to sign in, from where, and whether it worked. It has different retention,
-- different indexes, and one property the general trail cannot offer — ITS ROWS MUST SURVIVE A REJECTED
-- REQUEST. A failed sign-in rolls its transaction back; the record of the attempt must not go with it.
--
-- THERE IS NO occurred_at COLUMN, and its absence is deliberate. BaseEntity already supplies created_at,
-- and for an append-only event the two are the same moment. Two columns holding one fact is two columns
-- that can disagree — and the first time they do, nobody knows which to believe.

CREATE TABLE auth_audit_events
(
    id              bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             uuid         NOT NULL,

    -- NULLABLE, BOTH OF THEM, AND THAT IS THE POINT. A failed sign-in against a username that does not
    -- exist has no principal to name — and that row is precisely the one worth having. A NOT NULL here
    -- would force the code to either invent an identifier or skip the record, and it would skip it.
    principal_type  varchar(32),
    principal_uid   uuid,

    event_type      varchar(64)  NOT NULL,

    -- What the caller typed. Stored so an operator can see that somebody has been trying 'admin',
    -- 'administrator', 'root' in turn — a pattern invisible if only resolved accounts are recorded.
    identifier_used varchar(128),

    -- varchar(45) fits an IPv6 address in its longest textual form.
    source_ip       varchar(45),
    user_agent      varchar(255),

    created_at      timestamp    NOT NULL,
    updated_at      timestamp    NOT NULL
);

CREATE UNIQUE INDEX ux_auth_audit_events_uid ON auth_audit_events (uid);

-- "What has this account been doing", newest first. The composite ordering matters: the same query with
-- only principal_uid indexed still sorts the whole matching set.
CREATE INDEX ix_auth_audit_events_principal ON auth_audit_events (principal_uid, created_at DESC);

-- "What has this address been doing" — the query that finds a spray across many accounts, which is
-- invisible from any single account's history.
CREATE INDEX ix_auth_audit_events_source_ip ON auth_audit_events (source_ip, created_at DESC);

-- "How many failures in the last hour", across everything. Without this the answer is a full scan of a
-- table that grows with every request that touches a credential.
CREATE INDEX ix_auth_audit_events_type_created ON auth_audit_events (event_type, created_at DESC);
