-- identity-access V4 — which operators a staff member serves, and the company that bounds them.
--
-- MANY OPERATORS PER PERSON, deliberately. A shared-services employee covering two depots is ONE account
-- with two memberships, not two accounts with two passwords and two audit trails.
--
-- BUT ALL OF THEM UNDER ONE COMPANY. The tenancy hierarchy is Company -> Brand -> Operator -> Branch, and
-- an operator staff member belongs to exactly one company. Letting somebody hold memberships across two
-- companies would mean one credential reaching two unrelated businesses' data — a cross-tenant breach
-- with no exploit required, just a mis-click on an admin screen.
--
-- The enforcement below is STRUCTURAL rather than a service check, and that distinction is the point: a
-- check in application code has to be repeated at every place a membership is created, and the one that
-- is forgotten fails silently. A composite foreign key cannot be forgotten.

-- ─────────────────────── the company a staff member belongs to ───────────────────────

ALTER TABLE staff_identities
    ADD COLUMN company_uid uuid;

-- A bare handle into the tenancy module — no foreign key, for the usual reason: a constraint here would
-- weld identity-access to another module's tables and invert the dependency arrow.

-- ONLY OPERATOR STAFF HAVE A COMPANY, and they always do.
--
-- Platform staff (ROOT, ADMIN) belong to no tenancy, which is precisely why they may be scoped to all of
-- it. A partner belongs to a partner organisation, which is not a company in this hierarchy. Writing the
-- rule as an equivalence rather than two separate checks means neither half can be satisfied alone.
ALTER TABLE staff_identities
    ADD CONSTRAINT ck_staff_identities_company_matches_tenancy
        CHECK ((tenancy = 'OPERATOR') = (company_uid IS NOT NULL));

-- Required as the target of the composite foreign key below. It is not a uniqueness rule anyone needs on
-- its own — id is already the primary key — it exists so (staff_identity_id, company_uid) can reference it.
ALTER TABLE staff_identities
    ADD CONSTRAINT ux_staff_identities_id_company UNIQUE (id, company_uid);

-- ─────────────────────────────── the memberships ───────────────────────────────

CREATE TABLE staff_operators
(
    id                bigint    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid               uuid      NOT NULL,
    staff_identity_id bigint    NOT NULL REFERENCES staff_identities (id),

    -- NO FOREIGN KEY on either uid. Both point at the tenancy module's tables, and a constraint would
    -- invert the dependency arrow. A stale handle fails closed where it is resolved; it never corrupts a
    -- join, because there is no join.
    operator_uid      uuid      NOT NULL,

    -- The company this operator sits under. Duplicated from the operator's own record ON PURPOSE: it is
    -- what the constraint below compares against, and identity-access cannot join to tenancy to look it
    -- up. It is written once when the membership is created and never updated — an operator does not
    -- change company.
    company_uid       uuid      NOT NULL,

    created_at        timestamp NOT NULL,
    updated_at        timestamp NOT NULL,

    -- THE CROSS-COMPANY GUARD. A membership may only be attached to a staff member whose company_uid is
    -- the same value. Postgres enforces the pair, so a row linking an operator of company B to a staff
    -- member of company A cannot be written at all — not by this application, not by a data fix, not by a
    -- future admin surface that forgot to check.
    --
    -- It also means platform staff (company_uid NULL) can hold NO memberships: there is no non-null value
    -- that would match, and company_uid here is NOT NULL. That is correct — they are scoped to every
    -- operator and need none.
    CONSTRAINT fk_staff_operators_same_company
        FOREIGN KEY (staff_identity_id, company_uid) REFERENCES staff_identities (id, company_uid)
);

CREATE UNIQUE INDEX ux_staff_operators_uid ON staff_operators (uid);

-- One membership per (person, operator). Makes linking idempotent, and makes unlinking remove the
-- membership rather than one of two.
CREATE UNIQUE INDEX ux_staff_operators_pair ON staff_operators (staff_identity_id, operator_uid);

-- Every sign-in resolves the holder's memberships through this column.
CREATE INDEX ix_staff_operators_staff ON staff_operators (staff_identity_id);

-- "Which staff serve this operator" — the reverse lookup an operator-facing admin screen asks, which the
-- index above cannot answer.
CREATE INDEX ix_staff_operators_operator ON staff_operators (operator_uid);
