-- identity-access V5 — one-time tokens for setting a password.
--
-- WHY A TOKEN RATHER THAN AN ADMINISTRATOR TYPING A PASSWORD. An account is provisioned PENDING with no
-- credential, so something has to give it its first one. If that something is "an administrator sets a
-- temporary password", then every account's first password is known to somebody else, and the audit trail
-- can never distinguish the holder's actions from that person's. A token the holder redeems themselves is
-- what keeps "who provisioned the account" and "who knows its password" separate.
--
-- The same mechanism serves a forgotten password, so there is one path rather than two.

CREATE TABLE staff_password_resets
(
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid               uuid         NOT NULL,
    staff_identity_id bigint       NOT NULL REFERENCES staff_identities (id),

    -- THE HASH, NEVER THE TOKEN. A reset token is a bearer credential: whoever holds it can set the
    -- password. Storing it in the clear means a database dump — or anyone with read access to this table —
    -- can take over every account with a live reset, without needing a single password.
    --
    -- SHA-256 rather than the password encoder, and the reason is worth stating because it looks like a
    -- downgrade. A redemption arrives with a token and nothing else — the caller has not proved which
    -- account they are — so the token must be LOOKED UP, and a salted adaptive hash produces a different
    -- output every time and cannot be. The slow-hash argument does not apply here anyway: it exists to make
    -- guessing a human-chosen password expensive, and this value is 256 bits of randomness the holder never
    -- chose. Hex of SHA-256 is exactly 64 characters.
    token_hash        varchar(64)  NOT NULL,

    expires_at        timestamp    NOT NULL,

    -- Null until redeemed. The row is KEPT rather than deleted: "this reset was used, at this time" is
    -- exactly the question asked when an account turns out to have been taken over, and a delete answers it
    -- with silence.
    consumed_at       timestamp,

    -- Who issued it. An administrator cannot see the token after the response, but they did cause it to
    -- exist, and a takeover investigation starts here.
    issued_by_uid     uuid         NOT NULL,

    created_at        timestamp    NOT NULL,
    updated_at        timestamp    NOT NULL
);

CREATE UNIQUE INDEX ux_staff_password_resets_uid ON staff_password_resets (uid);

-- AT MOST ONE LIVE RESET PER ACCOUNT.
--
-- Without this, issuing a second reset leaves the first one working: an administrator who reissues because
-- "the link didn't arrive" has quietly created two credentials for one account, and the one that went
-- astray stays valid until it expires. The service supersedes outstanding resets when it issues a new one,
-- and this index is what makes that a guarantee rather than a code path somebody can forget.
--
-- Partial, so consumed rows do not compete — an account may have any number of spent resets in its history
-- and exactly one that still works.
CREATE UNIQUE INDEX ux_staff_password_resets_live
    ON staff_password_resets (staff_identity_id)
    WHERE consumed_at IS NULL;

-- Redemption looks a token up by its hash and nothing else; it cannot name the account, because the caller
-- has not proved which account they are. Unique, because two accounts sharing a token hash would mean the
-- randomness had collided and the lookup would have to choose one — better to refuse the write.
CREATE UNIQUE INDEX ux_staff_password_resets_token ON staff_password_resets (token_hash);
