-- identity-access V6 — agent login identities and their PIN material.
--
-- THIS MODULE OWNS THE LOGIN AND NOTHING ELSE ABOUT AN AGENT. Who an agent is, what they may sell, for
-- whom and under what limits, belongs to the `agent` module — which is WAVE 6 to this module's WAVE 2 and
-- therefore cannot be depended on here, even in principle. The consequence is deliberate and permanent:
-- an agent principal's permission set is EMPTY BY CONSTRUCTION. Authorisation for an agent is the audience
-- gate plus that module's own selling grants, and never this module's permission catalog.
--
-- NOTE WHICH WAY THE HANDLE POINTS. There is no agent_uid column here. The login stands alone, and the
-- `agent` module — being four waves later — holds the reference to THIS table's uid. That direction is the
-- only one that works: a column here would have to be populated with the uid of a record that does not yet
-- exist, by a module that cannot see it.
--
-- The shape mirrors staff: identity in one table, secret in another. Same reason — a query that reads who
-- somebody is must not drag a credential hash into memory, and the secret can be replaced without touching
-- the row a hundred others refer to by uid.

CREATE TABLE agent_identities
(
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid          uuid         NOT NULL,

    -- What the agent types to sign in. A phone number, not a username: these are field sellers with
    -- handsets, and a username would be one more thing to lose.
    --
    -- STORED CANONICAL — E.164, normalised in Java before it ever reaches here. 0712345678, 255712345678
    -- and +255712345678 are one phone, and storing them as typed would let one person hold three identities
    -- while every lookup found none of them. The staff tables solve the same problem with a functional
    -- index on lower(username); a phone number cannot be canonicalised by a SQL expression, so it is
    -- canonicalised on the way in and this column holds only the result.
    msisdn       varchar(20)  NOT NULL,

    display_name varchar(128) NOT NULL,

    -- Reuses the staff AccountStatus vocabulary, including PENDING meaning "provisioned, no PIN yet".
    status       varchar(32)  NOT NULL,

    created_at   timestamp    NOT NULL,
    updated_at   timestamp    NOT NULL
);

CREATE UNIQUE INDEX ux_agent_identities_uid ON agent_identities (uid);

-- ONE LOGIN PER PHONE. Without it two identities could share a number, the sign-in lookup would have to
-- choose one silently, and — worse — one person's failures would be split across two counters so neither
-- ever reached the lockout threshold.
CREATE UNIQUE INDEX ux_agent_identities_msisdn ON agent_identities (msisdn);

-- THE CANONICAL FORM IS ENFORCED HERE, not merely produced by the code that writes it.
--
-- Java canonicalises on the way in, and this is what makes that a guarantee instead of a habit. A row
-- inserted by a data fix, a future admin surface, or a test fixture that skipped the normaliser would
-- otherwise sit in the table unreachable: every sign-in canonicalises before looking up, so a
-- non-canonical row is a login nobody can ever use and nothing reports.
ALTER TABLE agent_identities
    ADD CONSTRAINT ck_agent_identities_msisdn_e164 CHECK (msisdn ~ '^\+[1-9][0-9]{7,14}$');

CREATE TABLE agent_credentials
(
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid               uuid         NOT NULL,
    agent_identity_id bigint       NOT NULL REFERENCES agent_identities (id),

    -- Hashed with the same adaptive encoder as a password, and that buys MUCH LESS here — a 6-digit PIN is
    -- a million candidates, which any attacker holding this column can exhaust offline whatever the work
    -- factor. The hash is still correct; it is simply not the defence. The defence is that the PIN cannot
    -- be guessed ONLINE, which is what the lockout below and the rate limiting of slice 8 are for.
    pin_hash          varchar(255) NOT NULL,

    pin_updated_at    timestamp    NOT NULL,
    failed_attempts   integer      NOT NULL DEFAULT 0,
    locked_until      timestamp,

    -- Set when an agent is provisioned with a PIN somebody else has necessarily seen. The route that
    -- completes it arrives with agent provisioning, exactly as must_change_password shipped in slice 1 and
    -- was completed in slice 6.
    must_change_pin   boolean      NOT NULL DEFAULT false,

    created_at        timestamp    NOT NULL,
    updated_at        timestamp    NOT NULL
);

CREATE UNIQUE INDEX ux_agent_credentials_uid ON agent_credentials (uid);

-- ONE CREDENTIAL PER IDENTITY. Two live PINs for one agent would mean only one of them carried the failure
-- counter, so guessing against the other would never lock anything.
CREATE UNIQUE INDEX ux_agent_credentials_identity ON agent_credentials (agent_identity_id);
