-- identity-access V7 — sessions, and the refresh tokens that extend them without a fresh sign-in.
--
-- WHY THIS EXISTS AT ALL. An access token is stateless and short: it carries a snapshot of authority and is
-- trusted, unread against any table, until it expires. That is what keeps the hot path off the database, and
-- it is also why there has been no way to end a session early — nothing to revoke. This slice adds the one
-- piece of server-side state that was deliberately absent: a session, and a rotating credential that renews
-- it. The access token stays exactly as it was; revocation acts on the session, and the access token simply
-- outlives it by at most its own short TTL.
--
-- WHY A REFRESH TOKEN AND NOT A LONGER ACCESS TOKEN. Lengthening the access token to avoid re-authentication
-- would lengthen the window in which a leaked one works and a revoked grant stays effective — the two costs
-- the short lifetime buys down. A refresh token moves the long-lived credential OFF the request path: it is
-- presented only to /refresh, never as a bearer on ordinary calls, so it is exposed far less and can be made
-- revocable and single-use in a way a bearer access token on every request cannot.
--
-- TWO TABLES, AND WHY. The SESSION is the thing that is revoked and that outlives any one token; the REFRESH
-- TOKEN is single-use and rotates on every renewal. Rotation with reuse detection needs the spent tokens to
-- remain recognisable after they are replaced — a replayed one is the signature of theft — so tokens are
-- their own rows, kept and marked consumed rather than deleted, exactly as staff_password_resets keeps a
-- spent reset. A session with only a current-token column could not tell a stolen replay from an unknown
-- token.

CREATE TABLE auth_sessions
(
    id             bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid            uuid         NOT NULL,

    -- PRINCIPAL-AGNOSTIC, exactly like auth_audit_events. A session serves a staff login or an agent login,
    -- and a single column cannot carry a foreign key to two different identity tables — so this is a bare
    -- uid handle plus the kind that tells which table it names, and the kind is also what a refresh keeps to
    -- the surface it was minted on. This is the same "hold a uid, not a foreign key" the module already uses
    -- for issued_by_uid and operator_uid; here it is forced rather than merely preferred.
    principal_uid  uuid         NOT NULL,
    principal_type varchar(32)  NOT NULL,

    -- THE ABSOLUTE CAP, set once at sign-in and never moved. Refreshing rotates the token but does not push
    -- this out, so a session lives at most this long from the sign-in that opened it, however active it is.
    -- A sliding expiry would let a continuously-used session live forever, which is precisely the unbounded
    -- credential a refresh token is supposed to avoid.
    expires_at     timestamp    NOT NULL,

    -- Advanced on every refresh. Not load-bearing for expiry — that is expires_at above — but it is what an
    -- "your active sessions" screen and an idle-timeout policy would both read, and recording it now costs a
    -- column rather than a later migration over live data.
    last_used_at   timestamp    NOT NULL,

    -- Null while the session is live. Set the moment it is ended early, with the reason alongside: a session
    -- has one current state but the interesting question is "what stopped it", and a reason column answers it
    -- without a join. Kept rather than deleted, so a revoked session is still auditable.
    revoked_at     timestamp,
    revoked_reason varchar(32),

    created_at     timestamp    NOT NULL,
    updated_at     timestamp    NOT NULL
);

CREATE UNIQUE INDEX ux_auth_sessions_uid ON auth_sessions (uid);

-- Ending every session a principal holds — a suspension, a password change, a recovery — reads by principal,
-- and so does listing them. Not unique: one principal legitimately holds many concurrent sessions, one per
-- device they signed in from.
CREATE INDEX ix_auth_sessions_principal ON auth_sessions (principal_uid, principal_type);

CREATE TABLE auth_refresh_tokens
(
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         uuid         NOT NULL,
    session_id  bigint       NOT NULL REFERENCES auth_sessions (id),

    -- THE HASH, NEVER THE TOKEN — the staff_password_resets argument verbatim. A refresh token is a bearer
    -- credential, so storing it in the clear makes read access to this table equivalent to a live session on
    -- every account that has one. SHA-256 rather than the adaptive encoder for the same reason a reset uses
    -- it: a refresh presents a token and nothing else, so the row must be found BY the token, which a salted
    -- hash cannot do; and the value is 256 bits of randomness the holder never chose, so the slow-hash
    -- defence buys nothing here. Hex of SHA-256 is exactly 64 characters.
    token_hash  varchar(64)  NOT NULL,

    -- Null until the token is used. A refresh SPENDS the presented token and issues a successor, so a used
    -- token is marked here rather than deleted — and that surviving mark is what makes reuse detectable: a
    -- token presented with consumed_at already set is a replay of a spent credential, and the session is
    -- revoked in response. See AuthSessionService.
    consumed_at timestamp,

    created_at  timestamp    NOT NULL,
    updated_at  timestamp    NOT NULL
);

CREATE UNIQUE INDEX ux_auth_refresh_tokens_uid ON auth_refresh_tokens (uid);

-- A refresh looks a token up by its hash and nothing else — the caller has proved nothing but possession —
-- so the lookup must be unique. Two rows sharing a hash would mean the randomness collided and the lookup
-- would have to choose; better to refuse the write.
CREATE UNIQUE INDEX ux_auth_refresh_tokens_hash ON auth_refresh_tokens (token_hash);

-- AT MOST ONE LIVE TOKEN PER SESSION — the rotation invariant, enforced rather than merely coded. A session
-- with two unconsumed tokens is one where a spent token was not marked, which is exactly the state reuse
-- detection depends on never existing. Partial, so the consumed history does not compete: a session may
-- accumulate any number of spent tokens and hold exactly one that still works. The service must consume the
-- old token and flush BEFORE inserting the new one, or Hibernate may order the insert first and trip this —
-- the same ordering staff_password_resets already demands of its live index.
CREATE UNIQUE INDEX ux_auth_refresh_tokens_live
    ON auth_refresh_tokens (session_id)
    WHERE consumed_at IS NULL;

CREATE INDEX ix_auth_refresh_tokens_session ON auth_refresh_tokens (session_id);
